"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.STATUS_CODES_TO_ABORT_ON = exports.REQUIRED_KEYS_FOR_AUTH = exports.DEFAULT_REST_ROOT = exports.DEFAULT_REST_BASE = exports.DEFAULT_REST_API_POSTFIX = exports.DEFAULT_OAUTH_APPS_ENDPOINT = void 0;
var STATUS_CODES_TO_ABORT_ON = [400, 401, 403, 404, 406, 410, 422];
exports.STATUS_CODES_TO_ABORT_ON = STATUS_CODES_TO_ABORT_ON;
var REQUIRED_KEYS_FOR_AUTH = ['access_token'];
exports.REQUIRED_KEYS_FOR_AUTH = REQUIRED_KEYS_FOR_AUTH;
var DEFAULT_REST_BASE = 'https://mastodon.social';
exports.DEFAULT_REST_BASE = DEFAULT_REST_BASE;
var DEFAULT_REST_API_POSTFIX = '/api/v1/';
exports.DEFAULT_REST_API_POSTFIX = DEFAULT_REST_API_POSTFIX;
var DEFAULT_REST_ROOT = DEFAULT_REST_BASE + DEFAULT_REST_API_POSTFIX;
exports.DEFAULT_REST_ROOT = DEFAULT_REST_ROOT;
var DEFAULT_OAUTH_APPS_ENDPOINT = "".concat(DEFAULT_REST_ROOT, "apps");
exports.DEFAULT_OAUTH_APPS_ENDPOINT = DEFAULT_OAUTH_APPS_ENDPOINT;